name: my_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

